name: ACR CD Pipeline


on:
  workflow_run:
    workflows: [ "ACR CI Pipeline" ]
    types:
      - completed

jobs:
  deploy:
    name: Deploy Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Extract Git commit hash and Set Variables
        id: version
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "LAMBDA_ARTIFACT_NAME=aws-cost-reporter-lambda-${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "LAMBDA_ARTIFACT_DIR=$GITHUB_WORKSPACE/artifact" >> $GITHUB_ENV
          echo "TF_PATH=$GITHUB_WORKSPACE/tf/" >> $GITHUB_ENV
          echo "TF_PLAN_PATH=$GITHUB_WORKSPACE/tf/plans/$GITHUB_RUN_ID-${GITHUB_SHA::7}.tfplan" >> $GITHUB_ENV
          echo "TELEPORT_CLUSTER_VERSION=$(curl https://${{ secrets.TELEPORT_CLUSTER_DOMAIN }}/v1/webapi/automaticupgrades/channel/default/version | sed 's/v//')" >> $GITHUB_ENV

      - name: Clean up previous artifact directory
        run: rm -rf ${{ env.LAMBDA_ARTIFACT_DIR }} /tmp/tbot /tmp/bot-config.yaml && mkdir -p ${{ env.LAMBDA_ARTIFACT_DIR }}

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.LAMBDA_ARTIFACT_NAME }}
          path: ${{ env.LAMBDA_ARTIFACT_DIR }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Fetch Teleport binaries
        uses: teleport-actions/setup@v1
        with:
          version: ${{ env.TELEPORT_CLUSTER_VERSION }}

      - name: Write tbot config
        run: |
          cat <<EOF > /tmp/bot-config.yaml
          version: v2
          onboarding:
            join_method: github
            token: ${{ secrets.TELEPORT_BOT_TOKEN }}
          storage:
            type: directory
            path: /tmp/tbot
            symlinks: try-secure
            acls: "off"
          services:
            - type: identity
              destination:
                type: directory
                path: /tmp/tbot
                symlinks: try-secure
                acls: "off"
              ssh_config: "on"
          debug: false
          auth_server: ${{ secrets.TELEPORT_CLUSTER_DOMAIN }}:443
          oneshot: true
          fips: false
          outputs:
            - type: workload-identity-x509
              destination:
                type: directory
                path: /tmp/tbot
              selector:
                name: ${{ secrets.TELEPORT_WORKLOAD_IDENTITY }}
          EOF



      - name: Get Teleport Status and Start Workload Identity
        run: |
          export TELEPORT_ANONYMOUS_TELEMETRY=1 
          tbot start -c /tmp/bot-config.yaml

      - name: Generate AWS Credentials using Workload Identity
        run: |

          curl https://rolesanywhere.amazonaws.com/releases/1.4.0/X86_64/Linux/aws_signing_helper --output /tmp/tbot/aws_signing_helper
          chmod +x /tmp/tbot/aws_signing_helper
          # Generate AWS credentials using the Teleport identity
          /tmp/tbot/aws_signing_helper credential-process \
            --certificate /tmp/tbot/svid.pem \
            --private-key /tmp/tbot/svid_key.pem \
            --profile-arn "${{ secrets.AWS_WORKLOAD_PROFILE_ARN }}" \
            --trust-anchor-arn "${{ secrets.AWS_WORKLOAD_TRUST_ANCHOR_ARN }}" \
            --role-arn "${{ secrets.AWS_WORKLOAD_ROLE_ARN }}" > /tmp/tbot/aws_creds.json

      - name: Export AWS Credentials
        run: |
          export AWS_ACCESS_KEY_ID=$(jq -r '.AccessKeyId' /tmp/tbot/aws_creds.json)
          export AWS_SECRET_ACCESS_KEY=$(jq -r '.SecretAccessKey' /tmp/tbot/aws_creds.json)
          export AWS_SESSION_TOKEN=$(jq -r '.SessionToken' /tmp/tbot/aws_creds.json)
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> $GITHUB_ENV

      - name: Install Terraform
        id: install-terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        id: init
        run: |
          cd ${{ env.TF_PATH }} && terraform init

      - name: Terraform Plan
        id: plan
        run: |
          export TF_VAR_slack_webhook_url="${{ secrets.SLACK_WEBHOOK_URL }}"
          cd ${{ env.TF_PATH }} && terraform plan --var-file=$GITHUB_WORKSPACE/tf/tfvars/${{ secrets.CI_CD_TFVARS }} -out="${{ env.TF_PLAN_PATH }}"

      - name: Terraform Apply
        id: apply
        run: |
          export TF_VAR_slack_webhook_url="${{ secrets.SLACK_WEBHOOK_URL }}"
          cd ${{ env.TF_PATH }} && terraform apply -auto-approve "${{ env.TF_PLAN_PATH }}"

      - name: Clean up
        if: always()
        run: pkill tbot || true && rm -rf ${{ env.LAMBDA_ARTIFACT_DIR }} /tmp/tbot /tmp/bot-config.yaml
