name: ACR CD Pipeline


on:
  workflow_run:
    workflows: [ "ACR CI Pipeline" ]
    types:
      - completed

jobs:
  deploy:
    name: Deploy Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Extract Git commit hash and Set Variables
        id: version
        run: |
          echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "LAMBDA_ARTIFACT_NAME=aws-cost-reporter-lambda-${GITHUB_SHA::7}" >> $GITHUB_ENV
          echo "LAMBDA_ARTIFACT_DIR=$GITHUB_WORKSPACE/artifact" >> $GITHUB_ENV
          echo "TF_PLAN_PATH=$GITHUB_WORKSPACE/plans/$GITHUB_RUN_ID-${GITHUB_SHA::7}.tfplan" >> $GITHUB_ENV
          echo "TELEPORT_CLUSTER_VERSION=$(curl https://${{ secrets.TELEPORT_CLUSTER_DOMAIN }}/v1/webapi/automaticupgrades/channel/default/version | sed 's/v//')" >> $GITHUB_ENV

      - name: Clean up previous artifact directory
        run: rm -rf ${{ env.LAMBDA_ARTIFACT_DIR }} /tmp/tbot && mkdir -p ${{ env.LAMBDA_ARTIFACT_DIR }}

      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.LAMBDA_ARTIFACT_NAME }}
          path: ${{ env.LAMBDA_ARTIFACT_DIR }}
          run-id: ${{ github.event.workflow_run.id }}
          github-token: ${{ github.token }}

      - name: Fetch Teleport binaries
        uses: teleport-actions/setup@v1
        with:
          version: ${{ env.TELEPORT_CLUSTER_VERSION }}

      - name: Fetch credentials using Machine ID
        id: auth
        uses: teleport-actions/auth@v2
        with:
          proxy: ${{ secrets.TELEPORT_CLUSTER_DOMAIN }}:443
          token: ${{ secrets.TELEPORT_BOT_TOKEN }}
          certificate-ttl: 10m
          anonymous-telemetry: 1

      #tbot start workload-identity-x509 --proxy-server $TELEPORT_PROXY_SERVER --join-method github --destination /tmp/workload-id --name-selector ${{ secrets.TELEPORT_WORKLOAD_ID_NAME_SELECTOR }}
      - name: Get Teleport Status and Start Workload Identity
        run: |
          export TELEPORT_ANONYMOUS_TELEMETRY=1 
          tsh status
          sleep 5
          echo ${{ secrets.TBOT_CONFIG }} >> /tmp/bot-config.yaml
          tbot start -c /tmp/bot-config.yaml --proxy-server $TELEPORT_PROXY_SERVER

      - name: Generate AWS Credentials using Workload Identity
        run: |

          curl https://rolesanywhere.amazonaws.com/releases/1.4.0/X86_64/Linux/aws_signing_helper --output /tmp/tbot/aws_signing_helper
          chmod +x /tmp/aws_signing_helper
          # Generate AWS credentials using the Teleport identity
          /tmp/tbot/aws_signing_helper credential-process \
            --certificate /tmp/tbot/svid.pem \
            --private-key /tmp/tbot/svid_key.pem \
            --profile-arn "${{ secrets.AWS_WORKLOAD_PROFILE_ARN }}" \
            --trust-anchor-arn "${{ secrets.AWS_WORKLOAD_TRUST_ANCHOR_ARN }}" \
            --role-arn "${{ secrets.AWS_WORKLOAD_ROLE_ARN }}" > /tmp/tbot/aws_creds.json

      - name: Export AWS Credentials
        run: |
          export AWS_ACCESS_KEY_ID=$(jq -r '.AccessKeyId' /tmp/tbot/aws_creds.json)
          export AWS_SECRET_ACCESS_KEY=$(jq -r '.SecretAccessKey' /tmp/tbot/aws_creds.json)
          export AWS_SESSION_TOKEN=$(jq -r '.SessionToken' /tmp/tbot/aws_creds.json)
          echo "AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}" >> $GITHUB_ENV
          echo "AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}" >> $GITHUB_ENV

      - name: Terraform Init
        run: |
          terraform init

      - name: Terraform Plan
        run: |
          terraform plan --var-file=$GITHUB_WORKSPACE/tfvars/${{ env.CI_CD_TFVARS }} -out="${{ env.TF_PLAN_PATH }}"
#
#      - name: Terraform Apply
#        run: |
#          # terraform apply -auto-approve "${{ env.TF_PLAN_PATH }}"
#           echo "Don't enable apply yet"
#
      - name: Clean up
        if: always()
        run: pkill tbot || true && rm -rf ${{ env.LAMBDA_ARTIFACT_DIR }} /tmp/tbot /tmp/bot-config.yaml
